"""initial schema

Revision ID: 7fbedb4c7fce
Revises: 
Create Date: 2026-08-08 18:12:59.210665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fbedb4c7fce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('normalized_value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_aliases_company_id'), 'company_aliases', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_aliases_normalized_value'), 'company_aliases', ['normalized_value'], unique=False)
    op.create_index(op.f('ix_company_aliases_value'), 'company_aliases', ['value'], unique=False)
    op.add_column('companies', sa.Column('canonical_name_normalized', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_companies_canonical_name_normalized'), 'companies', ['canonical_name_normalized'], unique=False)
    op.add_column('company_emails', sa.Column('normalized_value', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_company_emails_normalized_value'), 'company_emails', ['normalized_value'], unique=False)
    op.add_column('company_phone_numbers', sa.Column('normalized_value', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_company_phone_numbers_normalized_value'), 'company_phone_numbers', ['normalized_value'], unique=False)
    op.add_column('company_websites', sa.Column('normalized_value', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_company_websites_normalized_value'), 'company_websites', ['normalized_value'], unique=False)
    op.add_column('discoveries', sa.Column('resolved_company_id', sa.String(length=20), nullable=True))
    op.add_column('discoveries', sa.Column('resolution_status', sa.String(), nullable=False))
    op.add_column('discoveries', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('discoveries', sa.Column('phone_numbers', sa.JSON(), nullable=False))
    op.add_column('discoveries', sa.Column('email', sa.String(), nullable=True))
    op.add_column('discoveries', sa.Column('website', sa.String(), nullable=True))
    op.add_column('discoveries', sa.Column('social_links', sa.JSON(), nullable=False))
    op.add_column('discoveries', sa.Column('product_types', sa.JSON(), nullable=False))
    op.add_column('discoveries', sa.Column('payment_methods', sa.JSON(), nullable=False))
    op.add_column('discoveries', sa.Column('year_founded', sa.Integer(), nullable=True))
    op.add_column('discoveries', sa.Column('employee_count', sa.String(), nullable=True))
    op.add_column('discoveries', sa.Column('business_locations', sa.Integer(), nullable=True))
    op.add_column('discoveries', sa.Column('country', sa.String(), nullable=False))
    op.add_column('discoveries', sa.Column('state', sa.String(), nullable=False))
    op.add_column('discoveries', sa.Column('city', sa.String(), nullable=False))
    op.add_column('discoveries', sa.Column('root', sa.String(), nullable=True))
    op.add_column('discoveries', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('discoveries', sa.Column('sector', sa.String(), nullable=True))
    op.add_column('discoveries', sa.Column('category', sa.String(), nullable=False))
    op.add_column('discoveries', sa.Column('subcategory', sa.String(), nullable=True))
    op.add_column('discoveries', sa.Column('listing_url', sa.String(), nullable=False))
    op.add_column('discoveries', sa.Column('page_number', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_discoveries_resolved_company_id'), 'discoveries', ['resolved_company_id'], unique=False)
    op.drop_constraint(op.f('discoveries_company_id_fkey'), 'discoveries', type_='foreignkey')
    op.create_foreign_key(None, 'discoveries', 'companies', ['resolved_company_id'], ['id'])
    op.drop_column('discoveries', 'company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discoveries', sa.Column('company_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'discoveries', type_='foreignkey')
    op.create_foreign_key(op.f('discoveries_company_id_fkey'), 'discoveries', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_discoveries_resolved_company_id'), table_name='discoveries')
    op.drop_column('discoveries', 'page_number')
    op.drop_column('discoveries', 'listing_url')
    op.drop_column('discoveries', 'subcategory')
    op.drop_column('discoveries', 'category')
    op.drop_column('discoveries', 'sector')
    op.drop_column('discoveries', 'industry')
    op.drop_column('discoveries', 'root')
    op.drop_column('discoveries', 'city')
    op.drop_column('discoveries', 'state')
    op.drop_column('discoveries', 'country')
    op.drop_column('discoveries', 'business_locations')
    op.drop_column('discoveries', 'employee_count')
    op.drop_column('discoveries', 'year_founded')
    op.drop_column('discoveries', 'payment_methods')
    op.drop_column('discoveries', 'product_types')
    op.drop_column('discoveries', 'social_links')
    op.drop_column('discoveries', 'website')
    op.drop_column('discoveries', 'email')
    op.drop_column('discoveries', 'phone_numbers')
    op.drop_column('discoveries', 'resolved_at')
    op.drop_column('discoveries', 'resolution_status')
    op.drop_column('discoveries', 'resolved_company_id')
    op.drop_index(op.f('ix_company_websites_normalized_value'), table_name='company_websites')
    op.drop_column('company_websites', 'normalized_value')
    op.drop_index(op.f('ix_company_phone_numbers_normalized_value'), table_name='company_phone_numbers')
    op.drop_column('company_phone_numbers', 'normalized_value')
    op.drop_index(op.f('ix_company_emails_normalized_value'), table_name='company_emails')
    op.drop_column('company_emails', 'normalized_value')
    op.drop_index(op.f('ix_companies_canonical_name_normalized'), table_name='companies')
    op.drop_column('companies', 'canonical_name_normalized')
    op.drop_index(op.f('ix_company_aliases_value'), table_name='company_aliases')
    op.drop_index(op.f('ix_company_aliases_normalized_value'), table_name='company_aliases')
    op.drop_index(op.f('ix_company_aliases_company_id'), table_name='company_aliases')
    op.drop_table('company_aliases')
    # ### end Alembic commands ###
