"""add company field provenance

Revision ID: b40f930e6bd3
Revises: e65e37cd6ceb
Create Date: 2026-08-19 00:38:10.177502

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b40f930e6bd3'
down_revision: str | Sequence[str] | None = 'e65e37cd6ceb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_scalar_field_provenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=20), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('detail_url', sa.String(length=1024), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'field_name', name='uq_company_scalar_provenance_field')
    )
    op.create_index(op.f('ix_company_scalar_field_provenance_company_id'), 'company_scalar_field_provenance', ['company_id'], unique=False)
    op.create_table('company_set_field_provenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=20), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('detail_url', sa.String(length=1024), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'field_name', 'value', name='uq_company_set_provenance_field_value')
    )
    op.create_index(op.f('ix_company_set_field_provenance_company_id'), 'company_set_field_provenance', ['company_id'], unique=False)
    op.alter_column('discoveries', 'resolved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discoveries', 'resolved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_company_set_field_provenance_company_id'), table_name='company_set_field_provenance')
    op.drop_table('company_set_field_provenance')
    op.drop_index(op.f('ix_company_scalar_field_provenance_company_id'), table_name='company_scalar_field_provenance')
    op.drop_table('company_scalar_field_provenance')
    # ### end Alembic commands ###
