"""add discovery source detail url uniqueness

Revision ID: e65e37cd6ceb
Revises: 76145aace9b2
Create Date: 2026-08-17 00:19:10.484756

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e65e37cd6ceb'
down_revision: str | Sequence[str] | None = '76145aace9b2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_discoveries_source_detail_url', 'discoveries', ['source', 'detail_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_discoveries_source_detail_url', 'discoveries', type_='unique')
    # ### end Alembic commands ###
