from .models import Taxonomy

FINELIB_CATEGORY_MAP: dict[str, Taxonomy] = {
    "art-business": Taxonomy(
        industry="Art Business",
        sector="Art Business",
        category="Art Business",
    ),
    "automotive": Taxonomy(
        industry="Automotive",
        sector="Automotive",
        category="Automotive",
    ),
    "beauty-care": Taxonomy(
        industry="Beauty Care",
        sector="Beauty Care",
        category="Beauty Care",
    ),
    "business-services": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
    ),
    "chemical-service": Taxonomy(
        industry="Chemical Service",
        sector="Chemical Service",
        category="Chemical Service",
    ),
    "cleaning-services": Taxonomy(
        industry="Cleaning Services",
        sector="Cleaning Services",
        category="Cleaning Services",
    ),
    "clothing": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
    ),
    "construction": Taxonomy(
        industry="Construction",
        sector="Construction",
        category="Construction",
    ),
    "electrical-services": Taxonomy(
        industry="Electrical Services",
        sector="Electrical Services",
        category="Electrical Services",
    ),
    "energy": Taxonomy(
        industry="Energy",
        sector="Energy",
        category="Energy",
    ),
    "engineering-companies": Taxonomy(
        industry="Engineering Companies",
        sector="Engineering Companies",
        category="Engineering Companies",
    ),
    "entertainment": Taxonomy(
        industry="Entertainment",
        sector="Entertainment",
        category="Entertainment",
    ),
    "environmental-services": Taxonomy(
        industry="Environmental Services",
        sector="Environmental Services",
        category="Environmental Services",
    ),
    "exporters": Taxonomy(
        industry="Exporters",
        sector="Exporters",
        category="Exporters",
    ),
    "finance": Taxonomy(
        industry="Finance",
        sector="Finance",
        category="Finance",
    ),
    "fire-services": Taxonomy(
        industry="Fire Services",
        sector="Fire Services",
        category="Fire Services",
    ),
    "food": Taxonomy(
        industry="Food",
        sector="Food",
        category="Food",
    ),
    "furniture-dealers": Taxonomy(
        industry="Furniture Dealers",
        sector="Furniture Dealers",
        category="Furniture Dealers",
    ),
    "healthcare": Taxonomy(
        industry="Healthcare",
        sector="Healthcare",
        category="Healthcare",
    ),
    "home-and-living": Taxonomy(
        industry="Home and Living",
        sector="Home and Living",
        category="Home and Living",
    ),
    "human-resources": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
    ),
    "industrial-services": Taxonomy(
        industry="Industrial Services",
        sector="Industrial Services",
        category="Industrial Services",
    ),
    "manufacturing-industries": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
    ),
    "marketing-companies": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
    ),
    "metal-services": Taxonomy(
        industry="Metal Services",
        sector="Metal Services",
        category="Metal Services",
    ),
    "mining": Taxonomy(
        industry="Mining",
        sector="Mining",
        category="Mining",
    ),
    "packaging": Taxonomy(
        industry="Packaging",
        sector="Packaging",
        category="Packaging",
    ),
    "paper-companies": Taxonomy(
        industry="Paper Companies",
        sector="Paper Companies",
        category="Paper Companies",
    ),
    "parties-and-events": Taxonomy(
        industry="Parties and Events",
        sector="Parties and Events",
        category="Parties and Events",
    ),
    "personal-care": Taxonomy(
        industry="Personal Care",
        sector="Personal Care",
        category="Personal Care",
    ),
    "personal-development": Taxonomy(
        industry="Personal Development",
        sector="Personal Development",
        category="Personal Development",
    ),
    "pets-and-animals": Taxonomy(
        industry="Pets and Animals",
        sector="Pets and Animals",
        category="Pets and Animals",
    ),
    "printing-and-publishing": Taxonomy(
        industry="Printing and Publishing",
        sector="Printing and Publishing",
        category="Printing and Publishing",
    ),
    "real-estate": Taxonomy(
        industry="Real Estate",
        sector="Real Estate",
        category="Real Estate",
    ),
    "retail-services": Taxonomy(
        industry="Retail Services",
        sector="Retail Services",
        category="Retail Services",
    ),
    "rubber-products": Taxonomy(
        industry="Rubber Products",
        sector="Rubber Products",
        category="Rubber Products",
    ),
    "security-services": Taxonomy(
        industry="Security Services",
        sector="Security Services",
        category="Security Services",
    ),
    "telecommunication": Taxonomy(
        industry="Telecommunication",
        sector="Telecommunication",
        category="Telecommunication",
    ),
    "trading": Taxonomy(
        industry="Trading",
        sector="Trading",
        category="Trading",
    ),
    "transportation": Taxonomy(
        industry="Transportation",
        sector="Transportation",
        category="Transportation",
    ),
    "wood-and-timber": Taxonomy(
        industry="Wood and Timber",
        sector="Wood and Timber",
        category="Wood and Timber",
    ),
    "-mineral-exploration": Taxonomy(
        industry="Mining",
        sector="Mining",
        category="Mining",
        subcategory="Mineral Exploration",
    ),
    "-mining-contractors": Taxonomy(
        industry="Mining",
        sector="Mining",
        category="Mining",
        subcategory="Mining Contractors",
    ),
    "-mining-engineering": Taxonomy(
        industry="Mining",
        sector="Mining",
        category="Mining",
        subcategory="Mining Engineering",
    ),
    "3d-printing-services": Taxonomy(
        industry="Printing and Publishing",
        sector="Printing and Publishing",
        category="Printing and Publishing",
        subcategory="3D Printing Services",
    ),
    "abrasive-product": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Abrasive Product",
    ),
    "accounting": Taxonomy(
        industry="Finance",
        sector="Finance",
        category="Finance",
        subcategory="Accounting",
    ),
    "acoustic-product": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Acoustic Product",
    ),
    "adhesive-product": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Adhesive Product",
    ),
    "advertisement-companies": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="Advertisement Companies",
    ),
    "affiliate-marketing-companies": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="Affiliate Marketing Companies",
    ),
    "agents-and-brokers": Taxonomy(
        industry="Real Estate",
        sector="Real Estate",
        category="Real Estate",
        subcategory="Agents and Brokers",
    ),
    "agro-allied-products": Taxonomy(
        industry="Exporters",
        sector="Exporters",
        category="Exporters",
        subcategory="Agro Allied Products",
    ),
    "air-conditioning": Taxonomy(
        industry="Electrical Services",
        sector="Electrical Services",
        category="Electrical Services",
        subcategory="Air Conditioning",
    ),
    "alarm-systems": Taxonomy(
        industry="Security Services",
        sector="Security Services",
        category="Security Services",
        subcategory="Alarm Systems",
    ),
    "alternative-energy": Taxonomy(
        industry="Energy",
        sector="Energy",
        category="Energy",
        subcategory="Alternative Energy",
    ),
    "aluminum-producers": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Aluminum Producers",
    ),
    "apparel-manufacturing": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Apparel Manufacturing",
    ),
    "aquarium-and-pond-supplies": Taxonomy(
        industry="Pets and Animals",
        sector="Pets and Animals",
        category="Pets and Animals",
        subcategory="Aquarium and Pond Supplies",
    ),
    "architects": Taxonomy(
        industry="Construction",
        sector="Construction",
        category="Construction",
        subcategory="Architects",
    ),
    "asbestos-manufacturers": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Asbestos Manufacturers",
    ),
    "asset-management": Taxonomy(
        industry="Finance",
        sector="Finance",
        category="Finance",
        subcategory="Asset Management",
    ),
    "associations-and-bodies": Taxonomy(
        industry="Construction",
        sector="Construction",
        category="Construction",
        subcategory="Associations and Bodies",
    ),
    "auditors": Taxonomy(
        industry="Finance",
        sector="Finance",
        category="Finance",
        subcategory="Auditors",
    ),
    "automobile": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Automobile",
    ),
    "awnings-and-canopies": Taxonomy(
        industry="Parties and Events",
        sector="Parties and Events",
        category="Parties and Events",
        subcategory="Awnings and Canopies",
    ),
    "babies-wears": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Babies Wears",
    ),
    "baby-care": Taxonomy(
        industry="Healthcare",
        sector="Healthcare",
        category="Healthcare",
        subcategory="Baby Care",
    ),
    "baby-products": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Baby Products",
    ),
    "bakery": Taxonomy(
        industry="Food",
        sector="Food",
        category="Food",
        subcategory="Bakery",
    ),
    "banks": Taxonomy(
        industry="Finance",
        sector="Finance",
        category="Finance",
        subcategory="Banks",
    ),
    "banner-printing-companies": Taxonomy(
        industry="Printing and Publishing",
        sector="Printing and Publishing",
        category="Printing and Publishing",
        subcategory="Banner Printing Companies",
    ),
    "barbing-salons": Taxonomy(
        industry="Beauty Care",
        sector="Beauty Care",
        category="Beauty Care",
        subcategory="Barbing Salons",
    ),
    "barcode-system-suppliers": Taxonomy(
        industry="Retail Services",
        sector="Retail Services",
        category="Retail Services",
        subcategory="Barcode System Suppliers",
    ),
    "bars": Taxonomy(
        industry="Entertainment",
        sector="Entertainment",
        category="Entertainment",
        subcategory="Bars",
    ),
    "bath-supplies": Taxonomy(
        industry="Beauty Care",
        sector="Beauty Care",
        category="Beauty Care",
        subcategory="Bath Supplies",
    ),
    "battery": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Battery",
    ),
    "beauty-centres": Taxonomy(
        industry="Beauty Care",
        sector="Beauty Care",
        category="Beauty Care",
        subcategory="Beauty Centres",
    ),
    "beauty-schools": Taxonomy(
        industry="Beauty Care",
        sector="Beauty Care",
        category="Beauty Care",
        subcategory="Beauty Schools",
    ),
    "beds-and-bedding": Taxonomy(
        industry="Home and Living",
        sector="Home and Living",
        category="Home and Living",
        subcategory="Beds and Bedding",
    ),
    "beverage": Taxonomy(
        industry="Food",
        sector="Food",
        category="Food",
        subcategory="Beverage",
    ),
    "beverage-manufacturing": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Beverage Manufacturing",
    ),
    "beverages": Taxonomy(
        industry="Exporters",
        sector="Exporters",
        category="Exporters",
        subcategory="Beverages",
    ),
    "billboards": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="Billboards",
    ),
    "blacksmiths": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Blacksmiths",
    ),
    "boat-and-ship": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Boat and Ship",
    ),
    "body-art": Taxonomy(
        industry="Art Business",
        sector="Art Business",
        category="Art Business",
        subcategory="Body Art",
    ),
    "bottle-manufacturing": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Bottle Manufacturing",
    ),
    "bottled-water": Taxonomy(
        industry="Food",
        sector="Food",
        category="Food",
        subcategory="Bottled Water",
    ),
    "boxers-and-briefs": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Boxers and Briefs",
    ),
    "branding": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="Branding",
    ),
    "breast-care": Taxonomy(
        industry="Beauty Care",
        sector="Beauty Care",
        category="Beauty Care",
        subcategory="Breast Care",
    ),
    "brick-and-tiles": Taxonomy(
        industry="Construction",
        sector="Construction",
        category="Construction",
        subcategory="Brick and Tiles",
    ),
    "bridal-accessories": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Bridal Accessories",
    ),
    "building-construction": Taxonomy(
        industry="Construction",
        sector="Construction",
        category="Construction",
        subcategory="Building Construction",
    ),
    "bureau-de-change": Taxonomy(
        industry="Finance",
        sector="Finance",
        category="Finance",
        subcategory="Bureau De Change",
    ),
    "business-advisors": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Business Advisors",
    ),
    "business-centers": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Business Centers",
    ),
    "business-consultants": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Business Consultants",
    ),
    "business-developers": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Business Developers",
    ),
    "business-forms-printers": Taxonomy(
        industry="Printing and Publishing",
        sector="Printing and Publishing",
        category="Printing and Publishing",
        subcategory="Business Forms Printers",
    ),
    "business-funding-services": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Business Funding Services",
    ),
    "business-idea-resources": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Business Idea Resources",
    ),
    "business-loan-providers": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Business Loan Providers",
    ),
    "business-management": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Business Management",
    ),
    "business-networking-services": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Business Networking Services",
    ),
    "business-planning-services": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Business Planning Services",
    ),
    "business-sales-agents": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Business Sales Agents",
    ),
    "business-sales-services": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Business Sales Services",
    ),
    "business-support-services": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Business Support Services",
    ),
    "cake-makers": Taxonomy(
        industry="Parties and Events",
        sector="Parties and Events",
        category="Parties and Events",
        subcategory="Cake Makers",
    ),
    "car-battery": Taxonomy(
        industry="Automotive",
        sector="Automotive",
        category="Automotive",
        subcategory="Car Battery",
    ),
    "car-dealers": Taxonomy(
        industry="Automotive",
        sector="Automotive",
        category="Automotive",
        subcategory="Car Dealers",
    ),
    "car-rentals": Taxonomy(
        industry="Automotive",
        sector="Automotive",
        category="Automotive",
        subcategory="Car Rentals",
    ),
    "car-wash": Taxonomy(
        industry="Automotive",
        sector="Automotive",
        category="Automotive",
        subcategory="Car Wash",
    ),
    "career-coaching-providers": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="Career Coaching Providers",
    ),
    "career-management-and-planning": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="Career Management and Planning",
    ),
    "careers-advisors": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="Careers Advisors",
    ),
    "carpets-and-rugs": Taxonomy(
        industry="Home and Living",
        sector="Home and Living",
        category="Home and Living",
        subcategory="Carpets and Rugs",
    ),
    "cartoonists": Taxonomy(
        industry="Art Business",
        sector="Art Business",
        category="Art Business",
        subcategory="Cartoonists",
    ),
    "cash-register-suppliers": Taxonomy(
        industry="Retail Services",
        sector="Retail Services",
        category="Retail Services",
        subcategory="Cash Register Suppliers",
    ),
    "catalogue-design": Taxonomy(
        industry="Art Business",
        sector="Art Business",
        category="Art Business",
        subcategory="Catalogue Design",
    ),
    "catering-services": Taxonomy(
        industry="Food",
        sector="Food",
        category="Food",
        subcategory="Catering Services",
    ),
    "cement": Taxonomy(
        industry="Construction",
        sector="Construction",
        category="Construction",
        subcategory="Cement",
    ),
    "chefs": Taxonomy(
        industry="Food",
        sector="Food",
        category="Food",
        subcategory="Chefs",
    ),
    "chemical-manufacturers": Taxonomy(
        industry="Chemical Service",
        sector="Chemical Service",
        category="Chemical Service",
        subcategory="Chemical Manufacturers",
    ),
    "chemical-suppliers": Taxonomy(
        industry="Chemical Service",
        sector="Chemical Service",
        category="Chemical Service",
        subcategory="Chemical Suppliers",
    ),
    "children-clothes": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Children Clothes",
    ),
    "civil-and-structural-engineering": Taxonomy(
        industry="Engineering Companies",
        sector="Engineering Companies",
        category="Engineering Companies",
        subcategory="Civil and Structural Engineering",
    ),
    "cleaning-equipment": Taxonomy(
        industry="Cleaning Services",
        sector="Cleaning Services",
        category="Cleaning Services",
        subcategory="Cleaning Equipment",
    ),
    "clothing-accessories": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Clothing Accessories",
    ),
    "clothing-alteration": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Clothing Alteration",
    ),
    "clothing-boutiques": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Clothing Boutiques",
    ),
    "clothing-equipment": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Clothing Equipment",
    ),
    "clothing-merchants": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Clothing Merchants",
    ),
    "comedians": Taxonomy(
        industry="Entertainment",
        sector="Entertainment",
        category="Entertainment",
        subcategory="Comedians",
    ),
    "commercial-cleaning": Taxonomy(
        industry="Cleaning Services",
        sector="Cleaning Services",
        category="Cleaning Services",
        subcategory="Commercial Cleaning",
    ),
    "company-formation-experts": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Company Formation Experts",
    ),
    "computer-products": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Computer Products",
    ),
    "concrete": Taxonomy(
        industry="Construction",
        sector="Construction",
        category="Construction",
        subcategory="Concrete",
    ),
    "confectioneries": Taxonomy(
        industry="Food",
        sector="Food",
        category="Food",
        subcategory="Confectioneries",
    ),
    "construction-equipment": Taxonomy(
        industry="Construction",
        sector="Construction",
        category="Construction",
        subcategory="Construction Equipment",
    ),
    "construction-quality-control": Taxonomy(
        industry="Construction",
        sector="Construction",
        category="Construction",
        subcategory="Construction Quality Control",
    ),
    "contract-packing-services": Taxonomy(
        industry="Retail Services",
        sector="Retail Services",
        category="Retail Services",
        subcategory="Contract Packing Services",
    ),
    "contractors": Taxonomy(
        industry="Construction",
        sector="Construction",
        category="Construction",
        subcategory="Contractors",
    ),
    "copying": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Copying",
    ),
    "copywriters": Taxonomy(
        industry="Art Business",
        sector="Art Business",
        category="Art Business",
        subcategory="Copywriters",
    ),
    "corporate-entertainment": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Corporate Entertainment",
    ),
    "corporate-events": Taxonomy(
        industry="Parties and Events",
        sector="Parties and Events",
        category="Parties and Events",
        subcategory="Corporate Events",
    ),
    "corporate-research-companies": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Corporate Research Companies",
    ),
    "corporate-training": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Corporate Training",
    ),
    "cosmetics": Taxonomy(
        industry="Exporters",
        sector="Exporters",
        category="Exporters",
        subcategory="Cosmetics",
    ),
    "cosmetics-manufacturing": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Cosmetics Manufacturing",
    ),
    "cosmetics-stores": Taxonomy(
        industry="Beauty Care",
        sector="Beauty Care",
        category="Beauty Care",
        subcategory="Cosmetics Stores",
    ),
    "costumes": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Costumes",
    ),
    "courier-services": Taxonomy(
        industry="Transportation",
        sector="Transportation",
        category="Transportation",
        subcategory="Courier Services",
    ),
    "criminal-records-check-service": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="Criminal Records Check Service",
    ),
    "crude-oil": Taxonomy(
        industry="Exporters",
        sector="Exporters",
        category="Exporters",
        subcategory="Crude Oil",
    ),
    "customer-services-companies": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="Customer Services Companies",
    ),
    "customer-survey-providers": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Customer Survey Providers",
    ),
    "cv-writing-services": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="CV Writing Services",
    ),
    "dairy-product": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Dairy Product",
    ),
    "data-communication": Taxonomy(
        industry="Telecommunication",
        sector="Telecommunication",
        category="Telecommunication",
        subcategory="Data Communication",
    ),
    "data-services": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Data Services",
    ),
    "data-storage": Taxonomy(
        industry="Telecommunication",
        sector="Telecommunication",
        category="Telecommunication",
        subcategory="Data Storage",
    ),
    "design-agencies": Taxonomy(
        industry="Art Business",
        sector="Art Business",
        category="Art Business",
        subcategory="Design Agencies",
    ),
    "design-and-print-services": Taxonomy(
        industry="Printing and Publishing",
        sector="Printing and Publishing",
        category="Printing and Publishing",
        subcategory="Design and Print Services",
    ),
    "digital-printing-services": Taxonomy(
        industry="Printing and Publishing",
        sector="Printing and Publishing",
        category="Printing and Publishing",
        subcategory="Digital Printing Services",
    ),
    "direct-marketing-agencies": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="Direct Marketing Agencies",
    ),
    "disclosure-services": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="Disclosure Services",
    ),
    "distilled-water": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Distilled Water",
    ),
    "doors-and-window-services": Taxonomy(
        industry="Construction",
        sector="Construction",
        category="Construction",
        subcategory="Doors and Window Services",
    ),
    "driving-schools": Taxonomy(
        industry="Automotive",
        sector="Automotive",
        category="Automotive",
        subcategory="Driving Schools",
    ),
    "dry-cleaners-and-laundry": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Dry Cleaners and Laundry",
    ),
    "electric-power-utilities": Taxonomy(
        industry="Energy",
        sector="Energy",
        category="Energy",
        subcategory="Electric Power Utilities",
    ),
    "electrical-cables": Taxonomy(
        industry="Electrical Services",
        sector="Electrical Services",
        category="Electrical Services",
        subcategory="Electrical Cables",
    ),
    "electrical-engineers": Taxonomy(
        industry="Electrical Services",
        sector="Electrical Services",
        category="Electrical Services",
        subcategory="Electrical Engineers",
    ),
    "electrical-equipment": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Electrical Equipment",
    ),
    "electrical-generators": Taxonomy(
        industry="Electrical Services",
        sector="Electrical Services",
        category="Electrical Services",
        subcategory="Electrical Generators",
    ),
    "electrical-repairs": Taxonomy(
        industry="Electrical Services",
        sector="Electrical Services",
        category="Electrical Services",
        subcategory="Electrical Repairs",
    ),
    "electrical-spare-parts": Taxonomy(
        industry="Electrical Services",
        sector="Electrical Services",
        category="Electrical Services",
        subcategory="Electrical Spare Parts",
    ),
    "electrical-supplies": Taxonomy(
        industry="Electrical Services",
        sector="Electrical Services",
        category="Electrical Services",
        subcategory="Electrical Supplies",
    ),
    "electronics-dealers": Taxonomy(
        industry="Electrical Services",
        sector="Electrical Services",
        category="Electrical Services",
        subcategory="Electronics Dealers",
    ),
    "employee-relocation-advisors": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="Employee Relocation Advisors",
    ),
    "employee-survey-providers": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="Employee Survey Providers",
    ),
    "employment-training-providers": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="Employment Training Providers",
    ),
    "energy-associations": Taxonomy(
        industry="Energy",
        sector="Energy",
        category="Energy",
        subcategory="Energy Associations",
    ),
    "energy-trading": Taxonomy(
        industry="Energy",
        sector="Energy",
        category="Energy",
        subcategory="Energy Trading",
    ),
    "engineering-associations": Taxonomy(
        industry="Engineering Companies",
        sector="Engineering Companies",
        category="Engineering Companies",
        subcategory="Engineering Associations",
    ),
    "engineering-automation": Taxonomy(
        industry="Engineering Companies",
        sector="Engineering Companies",
        category="Engineering Companies",
        subcategory="Engineering Automation",
    ),
    "engineering-consultancy": Taxonomy(
        industry="Engineering Companies",
        sector="Engineering Companies",
        category="Engineering Companies",
        subcategory="Engineering Consultancy",
    ),
    "engineering-institutes": Taxonomy(
        industry="Engineering Companies",
        sector="Engineering Companies",
        category="Engineering Companies",
        subcategory="Engineering Institutes",
    ),
    "entrepreneurs": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Entrepreneurs",
    ),
    "environmental-cleaning": Taxonomy(
        industry="Cleaning Services",
        sector="Cleaning Services",
        category="Cleaning Services",
        subcategory="Environmental Cleaning",
    ),
    "environmental-engineering": Taxonomy(
        industry="Engineering Companies",
        sector="Engineering Companies",
        category="Engineering Companies",
        subcategory="Environmental Engineering",
    ),
    "epos-and-stock-control-systems": Taxonomy(
        industry="Retail Services",
        sector="Retail Services",
        category="Retail Services",
        subcategory="EPOS and Stock Control Systems",
    ),
    "estate-surveyors": Taxonomy(
        industry="Real Estate",
        sector="Real Estate",
        category="Real Estate",
        subcategory="Estate Surveyors",
    ),
    "event-decorators": Taxonomy(
        industry="Parties and Events",
        sector="Parties and Events",
        category="Parties and Events",
        subcategory="Event Decorators",
    ),
    "event-marketing-companies": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="Event Marketing Companies",
    ),
    "event-planners": Taxonomy(
        industry="Parties and Events",
        sector="Parties and Events",
        category="Parties and Events",
        subcategory="Event Planners",
    ),
    "eyelash-extensions": Taxonomy(
        industry="Beauty Care",
        sector="Beauty Care",
        category="Beauty Care",
        subcategory="Eyelash Extensions",
    ),
    "fabric-designers": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Fabric Designers",
    ),
    "facial-care": Taxonomy(
        industry="Beauty Care",
        sector="Beauty Care",
        category="Beauty Care",
        subcategory="Facial Care",
    ),
    "facility-managers": Taxonomy(
        industry="Real Estate",
        sector="Real Estate",
        category="Real Estate",
        subcategory="Facility Managers",
    ),
    "fashion-designers": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Fashion Designers",
    ),
    "fashion-schools": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Fashion Schools",
    ),
    "feminine-hygiene": Taxonomy(
        industry="Healthcare",
        sector="Healthcare",
        category="Healthcare",
        subcategory="Feminine Hygiene",
    ),
    "field-marketing-specialists": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="Field Marketing Specialists",
    ),
    "films-and-movies": Taxonomy(
        industry="Entertainment",
        sector="Entertainment",
        category="Entertainment",
        subcategory="Films and Movies",
    ),
    "financial-associations": Taxonomy(
        industry="Finance",
        sector="Finance",
        category="Finance",
        subcategory="Financial Associations",
    ),
    "financial-consultants": Taxonomy(
        industry="Finance",
        sector="Finance",
        category="Finance",
        subcategory="Financial Consultants",
    ),
    "financial-products": Taxonomy(
        industry="Finance",
        sector="Finance",
        category="Finance",
        subcategory="Financial Products",
    ),
    "fire-equipment": Taxonomy(
        industry="Security Services",
        sector="Security Services",
        category="Security Services",
        subcategory="Fire Equipment",
    ),
    "fire-equipment-suppliers": Taxonomy(
        industry="Fire Services",
        sector="Fire Services",
        category="Fire Services",
        subcategory="Fire Equipment Suppliers",
    ),
    "fire-extinguishers": Taxonomy(
        industry="Fire Services",
        sector="Fire Services",
        category="Fire Services",
        subcategory="Fire Extinguishers",
    ),
    "fire-protection-services": Taxonomy(
        industry="Fire Services",
        sector="Fire Services",
        category="Fire Services",
        subcategory="Fire Protection Services",
    ),
    "fire-risk-assessment-companies": Taxonomy(
        industry="Fire Services",
        sector="Fire Services",
        category="Fire Services",
        subcategory="Fire Risk Assessment Companies",
    ),
    "fire-safety-consultants": Taxonomy(
        industry="Fire Services",
        sector="Fire Services",
        category="Fire Services",
        subcategory="Fire Safety Consultants",
    ),
    "fire-safety-training-companies": Taxonomy(
        industry="Fire Services",
        sector="Fire Services",
        category="Fire Services",
        subcategory="Fire Safety Training Companies",
    ),
    "fitness": Taxonomy(
        industry="Healthcare",
        sector="Healthcare",
        category="Healthcare",
        subcategory="Fitness",
    ),
    "florist": Taxonomy(
        industry="Parties and Events",
        sector="Parties and Events",
        category="Parties and Events",
        subcategory="Florist",
    ),
    "flour-mills": Taxonomy(
        industry="Food",
        sector="Food",
        category="Food",
        subcategory="Flour Mills",
    ),
    "foam-manufacturing": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Foam Manufacturing",
    ),
    "foams-and-mattresses": Taxonomy(
        industry="Home and Living",
        sector="Home and Living",
        category="Home and Living",
        subcategory="Foams and Mattresses",
    ),
    "food-and-beverage-machinery": Taxonomy(
        industry="Food",
        sector="Food",
        category="Food",
        subcategory="Food and Beverage Machinery",
    ),
    "food-distribution": Taxonomy(
        industry="Food",
        sector="Food",
        category="Food",
        subcategory="Food Distribution",
    ),
    "food-industry": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Food Industry",
    ),
    "food-packing-and-bottling": Taxonomy(
        industry="Food",
        sector="Food",
        category="Food",
        subcategory="Food Packing and Bottling",
    ),
    "food-processing": Taxonomy(
        industry="Food",
        sector="Food",
        category="Food",
        subcategory="Food Processing",
    ),
    "food-stores": Taxonomy(
        industry="Food",
        sector="Food",
        category="Food",
        subcategory="Food Stores",
    ),
    "forwarding-and-clearing": Taxonomy(
        industry="Transportation",
        sector="Transportation",
        category="Transportation",
        subcategory="Forwarding and Clearing",
    ),
    "franchise-opportunities": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Franchise Opportunities",
    ),
    "frozen-foods": Taxonomy(
        industry="Exporters",
        sector="Exporters",
        category="Exporters",
        subcategory="Frozen Foods",
    ),
    "fruit-drinks": Taxonomy(
        industry="Food",
        sector="Food",
        category="Food",
        subcategory="Fruit Drinks",
    ),
    "fumigation-and-pest-control": Taxonomy(
        industry="Home and Living",
        sector="Home and Living",
        category="Home and Living",
        subcategory="Fumigation and Pest Control",
    ),
    "furniture": Taxonomy(
        industry="Home and Living",
        sector="Home and Living",
        category="Home and Living",
        subcategory="Furniture",
    ),
    "furniture-makers": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Furniture Makers",
    ),
    "garden-supplies": Taxonomy(
        industry="Home and Living",
        sector="Home and Living",
        category="Home and Living",
        subcategory="Garden Supplies",
    ),
    "hair-dressing-salon": Taxonomy(
        industry="Beauty Care",
        sector="Beauty Care",
        category="Beauty Care",
        subcategory="Hair Dressing Salon",
    ),
    "hair-supplies": Taxonomy(
        industry="Beauty Care",
        sector="Beauty Care",
        category="Beauty Care",
        subcategory="Hair Supplies",
    ),
    "handwriting-analysts": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="Handwriting Analysts",
    ),
    "handymen": Taxonomy(
        industry="Home and Living",
        sector="Home and Living",
        category="Home and Living",
        subcategory="Handymen",
    ),
    "headhunters": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="Headhunters",
    ),
    "healthcare-products": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Healthcare Products",
    ),
    "herbal-products": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Herbal Products",
    ),
    "hire-purchases": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Hire Purchases",
    ),
    "home-appliance": Taxonomy(
        industry="Home and Living",
        sector="Home and Living",
        category="Home and Living",
        subcategory="Home Appliance",
    ),
    "home-automation": Taxonomy(
        industry="Home and Living",
        sector="Home and Living",
        category="Home and Living",
        subcategory="Home Automation",
    ),
    "home-electronics": Taxonomy(
        industry="Home and Living",
        sector="Home and Living",
        category="Home and Living",
        subcategory="Home Electronics",
    ),
    "home-repairs": Taxonomy(
        industry="Home and Living",
        sector="Home and Living",
        category="Home and Living",
        subcategory="Home Repairs",
    ),
    "household-products": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Household Products",
    ),
    "hr-consultants": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="HR Consultants",
    ),
    "hr-investigations-companies": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="HR Investigations Companies",
    ),
    "hr-outsourcing-companies": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="HR Outsourcing Companies",
    ),
    "human-resource-software-design": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="Human Resource Software Design",
    ),
    "human-resources-associations": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="Human Resources Associations",
    ),
    "id-cards": Taxonomy(
        industry="Security Services",
        sector="Security Services",
        category="Security Services",
        subcategory="ID Cards",
    ),
    "immigration-services": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="Immigration Services",
    ),
    "industrial-coating": Taxonomy(
        industry="Industrial Services",
        sector="Industrial Services",
        category="Industrial Services",
        subcategory="Industrial Coating",
    ),
    "industrial-equipment": Taxonomy(
        industry="Industrial Services",
        sector="Industrial Services",
        category="Industrial Services",
        subcategory="Industrial Equipment",
    ),
    "industrial-machinery": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Industrial Machinery",
    ),
    "industrial-spare-parts": Taxonomy(
        industry="Industrial Services",
        sector="Industrial Services",
        category="Industrial Services",
        subcategory="Industrial Spare Parts",
    ),
    "industrial-supplies": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Industrial Supplies",
    ),
    "information-technology": Taxonomy(
        industry="Telecommunication",
        sector="Telecommunication",
        category="Telecommunication",
        subcategory="Information Technology",
    ),
    "insurance-companies": Taxonomy(
        industry="Finance",
        sector="Finance",
        category="Finance",
        subcategory="Insurance Companies",
    ),
    "interior-decorators": Taxonomy(
        industry="Home and Living",
        sector="Home and Living",
        category="Home and Living",
        subcategory="Interior Decorators",
    ),
    "interior-decors": Taxonomy(
        industry="Home and Living",
        sector="Home and Living",
        category="Home and Living",
        subcategory="Interior Decors",
    ),
    "international-marketing-agencies": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="International Marketing Agencies",
    ),
    "internet-marketing-agencies": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="Internet Marketing Agencies",
    ),
    "investment-services": Taxonomy(
        industry="Finance",
        sector="Finance",
        category="Finance",
        subcategory="Investment Services",
    ),
    "invitations": Taxonomy(
        industry="Parties and Events",
        sector="Parties and Events",
        category="Parties and Events",
        subcategory="Invitations",
    ),
    "janitorial-services": Taxonomy(
        industry="Cleaning Services",
        sector="Cleaning Services",
        category="Cleaning Services",
        subcategory="Janitorial Services",
    ),
    "jewelleries": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Jewelleries",
    ),
    "jewelry-manufacturing": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Jewelry Manufacturing",
    ),
    "kitchenware": Taxonomy(
        industry="Home and Living",
        sector="Home and Living",
        category="Home and Living",
        subcategory="Kitchenware",
    ),
    "land-surveyors": Taxonomy(
        industry="Real Estate",
        sector="Real Estate",
        category="Real Estate",
        subcategory="Land Surveyors",
    ),
    "landscape": Taxonomy(
        industry="Home and Living",
        sector="Home and Living",
        category="Home and Living",
        subcategory="Landscape",
    ),
    "landscaping": Taxonomy(
        industry="Real Estate",
        sector="Real Estate",
        category="Real Estate",
        subcategory="Landscaping",
    ),
    "language-translation-services": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Language Translation Services",
    ),
    "laundry-and-drycleaning-services": Taxonomy(
        industry="Cleaning Services",
        sector="Cleaning Services",
        category="Cleaning Services",
        subcategory="Laundry and Drycleaning Services",
    ),
    "lawns-specialist": Taxonomy(
        industry="Home and Living",
        sector="Home and Living",
        category="Home and Living",
        subcategory="Lawns Specialist",
    ),
    "leadership-training-courses": Taxonomy(
        industry="Personal Development",
        sector="Personal Development",
        category="Personal Development",
        subcategory="Leadership Training Courses",
    ),
    "learning-and-development-training": Taxonomy(
        industry="Personal Development",
        sector="Personal Development",
        category="Personal Development",
        subcategory="Learning and Development Training",
    ),
    "leather-products": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Leather Products",
    ),
    "leather-wears": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Leather Wears",
    ),
    "life-coach": Taxonomy(
        industry="Personal Development",
        sector="Personal Development",
        category="Personal Development",
        subcategory="Life Coach",
    ),
    "lightings-and-fittings": Taxonomy(
        industry="Home and Living",
        sector="Home and Living",
        category="Home and Living",
        subcategory="Lightings and Fittings",
    ),
    "lingerie": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Lingerie",
    ),
    "loans": Taxonomy(
        industry="Finance",
        sector="Finance",
        category="Finance",
        subcategory="Loans",
    ),
    "localisation-companies": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="Localisation Companies",
    ),
    "locksmith": Taxonomy(
        industry="Security Services",
        sector="Security Services",
        category="Security Services",
        subcategory="Locksmith",
    ),
    "magnetic-sweeping-services": Taxonomy(
        industry="Security Services",
        sector="Security Services",
        category="Security Services",
        subcategory="Magnetic Sweeping Services",
    ),
    "makeup-supplies": Taxonomy(
        industry="Beauty Care",
        sector="Beauty Care",
        category="Beauty Care",
        subcategory="Makeup Supplies",
    ),
    "manicure-and-pedicure": Taxonomy(
        industry="Beauty Care",
        sector="Beauty Care",
        category="Beauty Care",
        subcategory="Manicure and Pedicure",
    ),
    "market-research-and-development": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="Market Research and Development",
    ),
    "market-segmentation-and-target": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="Market Segmentation and Target",
    ),
    "marketing-consultants": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="Marketing Consultants",
    ),
    "marriage-agencies": Taxonomy(
        industry="Parties and Events",
        sector="Parties and Events",
        category="Parties and Events",
        subcategory="Marriage Agencies",
    ),
    "massage": Taxonomy(
        industry="Beauty Care",
        sector="Beauty Care",
        category="Beauty Care",
        subcategory="Massage",
    ),
    "material-handling": Taxonomy(
        industry="Industrial Services",
        sector="Industrial Services",
        category="Industrial Services",
        subcategory="Material Handling",
    ),
    "meat-and-poultry": Taxonomy(
        industry="Food",
        sector="Food",
        category="Food",
        subcategory="Meat and Poultry",
    ),
    "media-marketing-agencies": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="Media Marketing Agencies",
    ),
    "medical-bookkeeping-companies": Taxonomy(
        industry="Healthcare",
        sector="Healthcare",
        category="Healthcare",
        subcategory="Medical Bookkeeping Companies",
    ),
    "medical-equipment": Taxonomy(
        industry="Healthcare",
        sector="Healthcare",
        category="Healthcare",
        subcategory="Medical Equipment",
    ),
    "medical-products": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Medical Products",
    ),
    "men-care-and-grooming-supplies": Taxonomy(
        industry="Beauty Care",
        sector="Beauty Care",
        category="Beauty Care",
        subcategory="Men Care and Grooming Supplies",
    ),
    "merchandising-suppliers": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Merchandising Suppliers",
    ),
    "metals-manufacturing": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Metals Manufacturing",
    ),
    "micro-finance": Taxonomy(
        industry="Finance",
        sector="Finance",
        category="Finance",
        subcategory="Micro Finance",
    ),
    "milk-and-dairy-products": Taxonomy(
        industry="Food",
        sector="Food",
        category="Food",
        subcategory="Milk and Dairy Products",
    ),
    "mining-associations-and-agencies": Taxonomy(
        industry="Mining",
        sector="Mining",
        category="Mining",
        subcategory="Mining Associations and Agencies",
    ),
    "mining-equipment-and-tools": Taxonomy(
        industry="Mining",
        sector="Mining",
        category="Mining",
        subcategory="Mining Equipment and Tools",
    ),
    "mobile-marketing-services": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="Mobile Marketing Services",
    ),
    "modeling-agencies": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Modeling Agencies",
    ),
    "mortgage-services": Taxonomy(
        industry="Finance",
        sector="Finance",
        category="Finance",
        subcategory="Mortgage Services",
    ),
    "motivational-speakers": Taxonomy(
        industry="Personal Development",
        sector="Personal Development",
        category="Personal Development",
        subcategory="Motivational Speakers",
    ),
    "motor-cycle": Taxonomy(
        industry="Automotive",
        sector="Automotive",
        category="Automotive",
        subcategory="Motor Cycle",
    ),
    "multimedia": Taxonomy(
        industry="Telecommunication",
        sector="Telecommunication",
        category="Telecommunication",
        subcategory="Multimedia",
    ),
    "music": Taxonomy(
        industry="Entertainment",
        sector="Entertainment",
        category="Entertainment",
        subcategory="Music",
    ),
    "music-organizers": Taxonomy(
        industry="Parties and Events",
        sector="Parties and Events",
        category="Parties and Events",
        subcategory="Music Organizers",
    ),
    "nail-salons": Taxonomy(
        industry="Beauty Care",
        sector="Beauty Care",
        category="Beauty Care",
        subcategory="Nail Salons",
    ),
    "natural-hair-care": Taxonomy(
        industry="Beauty Care",
        sector="Beauty Care",
        category="Beauty Care",
        subcategory="Natural Hair Care",
    ),
    "nigerian-foodstuffs": Taxonomy(
        industry="Food",
        sector="Food",
        category="Food",
        subcategory="Nigerian Foodstuffs",
    ),
    "night-clubs": Taxonomy(
        industry="Entertainment",
        sector="Entertainment",
        category="Entertainment",
        subcategory="Night Clubs",
    ),
    "night-patrol": Taxonomy(
        industry="Security Services",
        sector="Security Services",
        category="Security Services",
        subcategory="Night Patrol",
    ),
    "nutritional-supplements": Taxonomy(
        industry="Healthcare",
        sector="Healthcare",
        category="Healthcare",
        subcategory="Nutritional Supplements",
    ),
    "office-services-companies": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Office Services Companies",
    ),
    "oil-and-gas": Taxonomy(
        industry="Energy",
        sector="Energy",
        category="Energy",
        subcategory="Oil and Gas",
    ),
    "oil-and-gas-refineries": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Oil and Gas Refineries",
    ),
    "online-payment": Taxonomy(
        industry="Finance",
        sector="Finance",
        category="Finance",
        subcategory="Online Payment",
    ),
    "packaging-machines": Taxonomy(
        industry="Packaging",
        sector="Packaging",
        category="Packaging",
        subcategory="Packaging Machines",
    ),
    "packaging-supplies": Taxonomy(
        industry="Packaging",
        sector="Packaging",
        category="Packaging",
        subcategory="Packaging Supplies",
    ),
    "paper-production-machinery": Taxonomy(
        industry="Paper Companies",
        sector="Paper Companies",
        category="Paper Companies",
        subcategory="Paper Production Machinery",
    ),
    "parts-and-supplies": Taxonomy(
        industry="Automotive",
        sector="Automotive",
        category="Automotive",
        subcategory="Parts and Supplies",
    ),
    "party-rentals": Taxonomy(
        industry="Parties and Events",
        sector="Parties and Events",
        category="Parties and Events",
        subcategory="Party Rentals",
    ),
    "payroll-services": Taxonomy(
        industry="Finance",
        sector="Finance",
        category="Finance",
        subcategory="Payroll Services",
    ),
    "pension-management": Taxonomy(
        industry="Finance",
        sector="Finance",
        category="Finance",
        subcategory="Pension Management",
    ),
    "perfumes-and-fragrance": Taxonomy(
        industry="Beauty Care",
        sector="Beauty Care",
        category="Beauty Care",
        subcategory="Perfumes and Fragrance",
    ),
    "personal-hygiene": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Personal Hygiene",
    ),
    "petrochemicals": Taxonomy(
        industry="Chemical Service",
        sector="Chemical Service",
        category="Chemical Service",
        subcategory="Petrochemicals",
    ),
    "pharmaceuticals": Taxonomy(
        industry="Healthcare",
        sector="Healthcare",
        category="Healthcare",
        subcategory="Pharmaceuticals",
    ),
    "pharmacies": Taxonomy(
        industry="Healthcare",
        sector="Healthcare",
        category="Healthcare",
        subcategory="Pharmacies",
    ),
    "phone-services": Taxonomy(
        industry="Telecommunication",
        sector="Telecommunication",
        category="Telecommunication",
        subcategory="Phone Services",
    ),
    "photographer": Taxonomy(
        industry="Parties and Events",
        sector="Parties and Events",
        category="Parties and Events",
        subcategory="Photographer",
    ),
    "photography": Taxonomy(
        industry="Art Business",
        sector="Art Business",
        category="Art Business",
        subcategory="Photography",
    ),
    "pipe-and-metal-coating": Taxonomy(
        industry="Metal Services",
        sector="Metal Services",
        category="Metal Services",
        subcategory="Pipe and Metal Coating",
    ),
    "plastic-printing-companies": Taxonomy(
        industry="Printing and Publishing",
        sector="Printing and Publishing",
        category="Printing and Publishing",
        subcategory="Plastic Printing Companies",
    ),
    "plastic-product": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Plastic Product",
    ),
    "plastics": Taxonomy(
        industry="Exporters",
        sector="Exporters",
        category="Exporters",
        subcategory="Plastics",
    ),
    "point-of-sale-solution-providers": Taxonomy(
        industry="Retail Services",
        sector="Retail Services",
        category="Retail Services",
        subcategory="Point Of Sale Solution Providers",
    ),
    "pollution-control": Taxonomy(
        industry="Environmental Services",
        sector="Environmental Services",
        category="Environmental Services",
        subcategory="Pollution Control",
    ),
    "polo-and-t_shirt": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Polo and T-Shirt",
    ),
    "pre_employment-screening-services": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="Pre-Employment Screening Services",
    ),
    "print-designers": Taxonomy(
        industry="Printing and Publishing",
        sector="Printing and Publishing",
        category="Printing and Publishing",
        subcategory="Print Designers",
    ),
    "printing-engineers": Taxonomy(
        industry="Printing and Publishing",
        sector="Printing and Publishing",
        category="Printing and Publishing",
        subcategory="Printing Engineers",
    ),
    "printing-machine": Taxonomy(
        industry="Printing and Publishing",
        sector="Printing and Publishing",
        category="Printing and Publishing",
        subcategory="Printing Machine",
    ),
    "printing-presses": Taxonomy(
        industry="Printing and Publishing",
        sector="Printing and Publishing",
        category="Printing and Publishing",
        subcategory="Printing Presses",
    ),
    "printing-products": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Printing Products",
    ),
    "printing-services": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Printing Services",
    ),
    "private-investigators": Taxonomy(
        industry="Security Services",
        sector="Security Services",
        category="Security Services",
        subcategory="Private Investigators",
    ),
    "promotional-agencies": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="Promotional Agencies",
    ),
    "proofreaders": Taxonomy(
        industry="Printing and Publishing",
        sector="Printing and Publishing",
        category="Printing and Publishing",
        subcategory="Proofreaders",
    ),
    "property-sign-erectors": Taxonomy(
        industry="Real Estate",
        sector="Real Estate",
        category="Real Estate",
        subcategory="Property Sign Erectors",
    ),
    "psychometric-testing": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="Psychometric Testing",
    ),
    "public-relations": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="Public Relations",
    ),
    "public-speaking-training-companies": Taxonomy(
        industry="Personal Development",
        sector="Personal Development",
        category="Personal Development",
        subcategory="Public Speaking Training Companies",
    ),
    "quality-control-companies": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="Quality Control Companies",
    ),
    "real-estate-developers": Taxonomy(
        industry="Real Estate",
        sector="Real Estate",
        category="Real Estate",
        subcategory="Real Estate Developers",
    ),
    "reception-venues": Taxonomy(
        industry="Parties and Events",
        sector="Parties and Events",
        category="Parties and Events",
        subcategory="Reception Venues",
    ),
    "recycling": Taxonomy(
        industry="Energy",
        sector="Energy",
        category="Energy",
        subcategory="Recycling",
    ),
    "registrar-office": Taxonomy(
        industry="Parties and Events",
        sector="Parties and Events",
        category="Parties and Events",
        subcategory="Registrar Office",
    ),
    "reprographic-services": Taxonomy(
        industry="Printing and Publishing",
        sector="Printing and Publishing",
        category="Printing and Publishing",
        subcategory="Reprographic Services",
    ),
    "residential-cleaning": Taxonomy(
        industry="Cleaning Services",
        sector="Cleaning Services",
        category="Cleaning Services",
        subcategory="Residential Cleaning",
    ),
    "restaurants": Taxonomy(
        industry="Food",
        sector="Food",
        category="Food",
        subcategory="Restaurants",
    ),
    "retail-and-shop-cleaning-companies": Taxonomy(
        industry="Cleaning Services",
        sector="Cleaning Services",
        category="Cleaning Services",
        subcategory="Retail and Shop Cleaning Companies",
    ),
    "road-construction": Taxonomy(
        industry="Construction",
        sector="Construction",
        category="Construction",
        subcategory="Road Construction",
    ),
    "rubber-stamp-suppliers": Taxonomy(
        industry="Printing and Publishing",
        sector="Printing and Publishing",
        category="Printing and Publishing",
        subcategory="Rubber Stamp Suppliers",
    ),
    "safes-and-locks": Taxonomy(
        industry="Security Services",
        sector="Security Services",
        category="Security Services",
        subcategory="Safes and Locks",
    ),
    "safety-equipment": Taxonomy(
        industry="Security Services",
        sector="Security Services",
        category="Security Services",
        subcategory="Safety Equipment",
    ),
    "sales-promotion-agencies": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="Sales Promotion Agencies",
    ),
    "salon-equipment": Taxonomy(
        industry="Beauty Care",
        sector="Beauty Care",
        category="Beauty Care",
        subcategory="Salon Equipment",
    ),
    "salt-manufacturers": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Salt Manufacturers",
    ),
    "sandblasting": Taxonomy(
        industry="Industrial Services",
        sector="Industrial Services",
        category="Industrial Services",
        subcategory="Sandblasting",
    ),
    "sanitary-paper": Taxonomy(
        industry="Healthcare",
        sector="Healthcare",
        category="Healthcare",
        subcategory="Sanitary Paper",
    ),
    "satellite-communications": Taxonomy(
        industry="Telecommunication",
        sector="Telecommunication",
        category="Telecommunication",
        subcategory="Satellite Communications",
    ),
    "sawmills-and-timber-industries": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Sawmills and Timber Industries",
    ),
    "scrap-metal": Taxonomy(
        industry="Metal Services",
        sector="Metal Services",
        category="Metal Services",
        subcategory="Scrap Metal",
    ),
    "seafood": Taxonomy(
        industry="Food",
        sector="Food",
        category="Food",
        subcategory="Seafood",
    ),
    "secretarial-services": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Secretarial Services",
    ),
    "security-consultants": Taxonomy(
        industry="Security Services",
        sector="Security Services",
        category="Security Services",
        subcategory="Security Consultants",
    ),
    "security-doors": Taxonomy(
        industry="Security Services",
        sector="Security Services",
        category="Security Services",
        subcategory="Security Doors",
    ),
    "security-equipments": Taxonomy(
        industry="Security Services",
        sector="Security Services",
        category="Security Services",
        subcategory="Security Equipments",
    ),
    "security-fences": Taxonomy(
        industry="Security Services",
        sector="Security Services",
        category="Security Services",
        subcategory="Security Fences",
    ),
    "security-gates": Taxonomy(
        industry="Security Services",
        sector="Security Services",
        category="Security Services",
        subcategory="Security Gates",
    ),
    "security-guards": Taxonomy(
        industry="Security Services",
        sector="Security Services",
        category="Security Services",
        subcategory="Security Guards",
    ),
    "security-locks": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Security Locks",
    ),
    "security-training-courses": Taxonomy(
        industry="Security Services",
        sector="Security Services",
        category="Security Services",
        subcategory="Security Training Courses",
    ),
    "sewage-treatment": Taxonomy(
        industry="Home and Living",
        sector="Home and Living",
        category="Home and Living",
        subcategory="Sewage Treatment",
    ),
    "sewing-machine-dealers": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Sewing Machine Dealers",
    ),
    "shoe-manufacturers": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Shoe Manufacturers",
    ),
    "shoes": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Shoes",
    ),
    "signage": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="Signage",
    ),
    "skin-care-products": Taxonomy(
        industry="Beauty Care",
        sector="Beauty Care",
        category="Beauty Care",
        subcategory="Skin Care Products",
    ),
    "sms-marketing-agencies": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="SMS Marketing Agencies",
    ),
    "snacks": Taxonomy(
        industry="Food",
        sector="Food",
        category="Food",
        subcategory="Snacks",
    ),
    "solid-minerals": Taxonomy(
        industry="Exporters",
        sector="Exporters",
        category="Exporters",
        subcategory="Solid Minerals",
    ),
    "spa": Taxonomy(
        industry="Beauty Care",
        sector="Beauty Care",
        category="Beauty Care",
        subcategory="Spa",
    ),
    "sports-marketing-specialists": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="Sports Marketing Specialists",
    ),
    "staff-training-companies": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Staff Training Companies",
    ),
    "stamping-and-engraving": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Stamping and Engraving",
    ),
    "stationary-manufacturing": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Stationary Manufacturing",
    ),
    "steel-erection": Taxonomy(
        industry="Industrial Services",
        sector="Industrial Services",
        category="Industrial Services",
        subcategory="Steel Erection",
    ),
    "steel-industries": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Steel Industries",
    ),
    "stock-clearance-companies": Taxonomy(
        industry="Retail Services",
        sector="Retail Services",
        category="Retail Services",
        subcategory="Stock Clearance Companies",
    ),
    "stock-exchange": Taxonomy(
        industry="Finance",
        sector="Finance",
        category="Finance",
        subcategory="Stock Exchange",
    ),
    "student-marketing-services": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="Student Marketing Services",
    ),
    "sugar-manufacturers": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Sugar Manufacturers",
    ),
    "sunglasses": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Sunglasses",
    ),
    "surveillance-services": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="Surveillance Services",
    ),
    "swimming-pool-design": Taxonomy(
        industry="Home and Living",
        sector="Home and Living",
        category="Home and Living",
        subcategory="Swimming Pool Design",
    ),
    "swimming-trunks": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Swimming Trunks",
    ),
    "t_shirt-printers": Taxonomy(
        industry="Printing and Publishing",
        sector="Printing and Publishing",
        category="Printing and Publishing",
        subcategory="T-Shirt Printers",
    ),
    "talent-management": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="Talent Management",
    ),
    "tarpaulin-manufacturers": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Tarpaulin Manufacturers",
    ),
    "team-building": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Team Building",
    ),
    "telecom-products": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Telecom Products",
    ),
    "telecommunication-associations": Taxonomy(
        industry="Telecommunication",
        sector="Telecommunication",
        category="Telecommunication",
        subcategory="Telecommunication Associations",
    ),
    "telecommunication-engineers": Taxonomy(
        industry="Telecommunication",
        sector="Telecommunication",
        category="Telecommunication",
        subcategory="Telecommunication Engineers",
    ),
    "telecommunication-industries": Taxonomy(
        industry="Telecommunication",
        sector="Telecommunication",
        category="Telecommunication",
        subcategory="Telecommunication industries",
    ),
    "telecommunication-providers": Taxonomy(
        industry="Telecommunication",
        sector="Telecommunication",
        category="Telecommunication",
        subcategory="Telecommunication Providers",
    ),
    "telecommunication-training": Taxonomy(
        industry="Telecommunication",
        sector="Telecommunication",
        category="Telecommunication",
        subcategory="Telecommunication Training",
    ),
    "telemarketing-companies": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="Telemarketing Companies",
    ),
    "tender-services": Taxonomy(
        industry="Business Services",
        sector="Business Services",
        category="Business Services",
        subcategory="Tender Services",
    ),
    "tent-makers": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Tent Makers",
    ),
    "textile-manufacturing": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Textile Manufacturing",
    ),
    "textile-mills": Taxonomy(
        industry="Manufacturing Industries",
        sector="Manufacturing Industries",
        category="Manufacturing Industries",
        subcategory="Textile Mills",
    ),
    "textiles": Taxonomy(
        industry="Exporters",
        sector="Exporters",
        category="Exporters",
        subcategory="Textiles",
    ),
    "textiles-and-fabrics": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Textiles and Fabrics",
    ),
    "tissue-paper-manufacturing": Taxonomy(
        industry="Paper Companies",
        sector="Paper Companies",
        category="Paper Companies",
        subcategory="Tissue Paper Manufacturing",
    ),
    "tobacco": Taxonomy(
        industry="Food",
        sector="Food",
        category="Food",
        subcategory="Tobacco",
    ),
    "trade-associations": Taxonomy(
        industry="Trading",
        sector="Trading",
        category="Trading",
        subcategory="Trade Associations",
    ),
    "trade-free-zones": Taxonomy(
        industry="Trading",
        sector="Trading",
        category="Trading",
        subcategory="Trade Free Zones",
    ),
    "trucking-services": Taxonomy(
        industry="Transportation",
        sector="Transportation",
        category="Transportation",
        subcategory="Trucking Services",
    ),
    "typesetters": Taxonomy(
        industry="Printing and Publishing",
        sector="Printing and Publishing",
        category="Printing and Publishing",
        subcategory="Typesetters",
    ),
    "tyres-and-tubes": Taxonomy(
        industry="Automotive",
        sector="Automotive",
        category="Automotive",
        subcategory="Tyres and Tubes",
    ),
    "uniforms-and-work-wears": Taxonomy(
        industry="Clothing",
        sector="Clothing",
        category="Clothing",
        subcategory="Uniforms and Work Wears",
    ),
    "ups-equipments": Taxonomy(
        industry="Telecommunication",
        sector="Telecommunication",
        category="Telecommunication",
        subcategory="UPS Equipments",
    ),
    "urban-and-regional-planning": Taxonomy(
        industry="Real Estate",
        sector="Real Estate",
        category="Real Estate",
        subcategory="Urban and Regional Planning",
    ),
    "used-cars": Taxonomy(
        industry="Automotive",
        sector="Automotive",
        category="Automotive",
        subcategory="Used Cars",
    ),
    "used-electrical-equipment": Taxonomy(
        industry="Electrical Services",
        sector="Electrical Services",
        category="Electrical Services",
        subcategory="Used Electrical Equipment",
    ),
    "valuers": Taxonomy(
        industry="Real Estate",
        sector="Real Estate",
        category="Real Estate",
        subcategory="Valuers",
    ),
    "videographer": Taxonomy(
        industry="Parties and Events",
        sector="Parties and Events",
        category="Parties and Events",
        subcategory="Videographer",
    ),
    "viral-marketing-designers": Taxonomy(
        industry="Marketing Companies",
        sector="Marketing Companies",
        category="Marketing Companies",
        subcategory="Viral Marketing Designers",
    ),
    "voice-coaches": Taxonomy(
        industry="Personal Development",
        sector="Personal Development",
        category="Personal Development",
        subcategory="Voice Coaches",
    ),
    "waste-management": Taxonomy(
        industry="Energy",
        sector="Energy",
        category="Energy",
        subcategory="Waste Management",
    ),
    "water-companies": Taxonomy(
        industry="Food",
        sector="Food",
        category="Food",
        subcategory="Water Companies",
    ),
    "waxing": Taxonomy(
        industry="Beauty Care",
        sector="Beauty Care",
        category="Beauty Care",
        subcategory="Waxing",
    ),
    "weaveon-and-attachments": Taxonomy(
        industry="Beauty Care",
        sector="Beauty Care",
        category="Beauty Care",
        subcategory="Weaveon and Attachments",
    ),
    "weddings": Taxonomy(
        industry="Parties and Events",
        sector="Parties and Events",
        category="Parties and Events",
        subcategory="Weddings",
    ),
    "welding": Taxonomy(
        industry="Metal Services",
        sector="Metal Services",
        category="Metal Services",
        subcategory="Welding",
    ),
    "wholesale-traders": Taxonomy(
        industry="Trading",
        sector="Trading",
        category="Trading",
        subcategory="Wholesale Traders",
    ),
    "windows": Taxonomy(
        industry="Home and Living",
        sector="Home and Living",
        category="Home and Living",
        subcategory="Windows",
    ),
    "workforce-management-consultancy": Taxonomy(
        industry="Human Resources",
        sector="Human Resources",
        category="Human Resources",
        subcategory="Workforce Management Consultancy",
    ),
}